### ISSUE TITLE
Blocking Waittime in View 

### ISSUE THREAD

**Issue by ronaldgithub** [erikdarlingdata/DarlingData#18]
**Version of the script**
SELECT @version = '1.0', @version_date = '20200301';

**What is the current behavior?**
The wait_time is updated for all individual events when you test the same blocking situation twice.
So if the wait on the first session was 10 sec and the other session is 20 sec, the first session is updated also with 20 sec.

**If the current behavior is a bug, please provide the steps to reproduce.**
Create a blocking situation check the waittime in the table dbo.keeper_HumanEvents_blocking 
Wait a little bit and do the step above again.

**What is the expected behavior?**
The wait_times of the two sessions should differ, group by transaction_id?

**Which versions of SQL Server and which OS are affected by this issue? Did this work in previous versions of our procedures?**
WIN10 / SQL2019

**Comment by erikdarlingdata** [comment]
Can you post a screenshot of what you mean? I'm not understanding the issue.


/* erikdarlingdata.com */
/* sql server performance tuning */
________________________________

**Comment by ronaldgithub** [comment]
>
![2020-03-16_12-10-43](https://user-images.githubusercontent.com/23001454/76770264-ece24680-679d-11ea-8080-2b178e8eabea.jpg)

**Comment by ronaldgithub** [comment]
All the past sessions got the last time value.

**Comment by ronaldgithub** [comment]
[cid:image001.jpg@01D5FBAB.F812F8F0]

Check the event_time against the wait_time, previous tests had different times..
I hop you understand it now.

Thank you very much for the code, I will use it a lot!

**Comment by erikdarlingdata** [comment]
Ooh I see, yeah. That was an oversight on my part. I should have had transaction id and monitor loop as join conditions in the update. I just pushed a few changes to the dev branch. Try that out!

Thanks for the report!

**Comment by ronaldgithub** [comment]
Thank you, I will try it now!

**Comment by ronaldgithub** [comment]
I still get them, downloaded the latest version.

[cid:image002.jpg@01D5FBAE.72567E50]

**Comment by erikdarlingdata** [comment]
I'm not really sure how many other join conditions I can add in here. Do you have any ideas? Can you post another screen shot of the data?

![image](https://user-images.githubusercontent.com/2136037/76772925-0ff9ff80-6778-11ea-83fa-1d1246851927.png)

**Comment by ronaldgithub** [comment]
I will use the ‘dev’ branch version... (soory)

**Comment by ronaldgithub** [comment]
A bit too many...

[cid:image002.jpg@01D5FBAF.8DB6BE70]

**Comment by ronaldgithub** [comment]
I will have a look at the code, I hope I can help you...

**Comment by ronaldgithub** [comment]
Just a thought...
Get the max_event_time.. and don’t do the cross apply?


select report.event_time
,report.database_name
,report.database_id
,report.object_id
,report.transaction_id
,report.resource_owner_type
,report.monitor_loop
,report.blocked_process_report
-- blocking
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@spid)[1]','int') AS blocking_spid
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/inputbuf/text())[1]', 'NVARCHAR(MAX)') AS blocking_text
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@status)[1]', 'NVARCHAR(100)') AS blocking_status
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@priority)[1]', 'NVARCHAR(100)') AS blocking_priority
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@trancount)[1]', 'NVARCHAR(100)') AS blocking_trancount
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@clientapp)[1]', 'NVARCHAR(100)') AS blocking_clientapp
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@hostname)[1]', 'NVARCHAR(100)') AS blocking_hostname
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@loginname)[1]', 'NVARCHAR(100)') AS blocking_loginname
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@currentdbname)[1]', 'NVARCHAR(100)') AS blocking_database
,report.blocked_process_report.value('(//blocked-process-report/blocking-process/process/@isolationlevel)[1]', 'NVARCHAR(100)') AS blocking_isolationlevel
-- blocked
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@spid)[1]','int') AS blocked_spid
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@transactionname)[1]', 'NVARCHAR(100)') AS blocked_transactionname
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/inputbuf/text())[1]', 'NVARCHAR(MAX)') AS blocked_text
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@waittime)[1]', 'NVARCHAR(100)') AS blocked_waittime
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@lasttranstarted)[1]', 'NVARCHAR(100)') AS blocked_lasttranstarted
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@lockMode)[1]', 'NVARCHAR(100)') AS blocked_lockmode
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@status)[1]', 'NVARCHAR(100)') AS blocked_status
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@priority)[1]', 'NVARCHAR(100)') AS blocked_priority
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@trancount)[1]', 'NVARCHAR(100)') AS blocked_trancount
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@clientapp)[1]', 'NVARCHAR(100)') AS blocked_clientapp
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@hostname)[1]', 'NVARCHAR(100)') AS blocked_hostname
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@loginname)[1]', 'NVARCHAR(100)') AS blocked_loginname
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@currentdbname)[1]', 'NVARCHAR(100)') AS blocked_database
,report.blocked_process_report.value('(//blocked-process-report/blocked-process/process/@isolationlevel)[1]', 'NVARCHAR(100)') AS blocked_isolationlevel
from (
SELECT DATEADD(MINUTE, DATEDIFF(MINUTE, GETUTCDATE(), SYSDATETIME()), c.value('@timestamp', 'DATETIME2')) AS event_time,
        DB_NAME(c.value('(data[@name="database_id"]/value)[1]', 'INT')) AS database_name,
        c.value('(data[@name="database_id"]/value)[1]', 'INT') AS database_id,
        c.value('(data[@name="object_id"]/value)[1]', 'INT') AS object_id,
        c.value('(data[@name="transaction_id"]/value)[1]', 'BIGINT') AS transaction_id,
        c.value('(data[@name="resource_owner_type"]/text)[1]', 'NVARCHAR(256)') AS resource_owner_type,
        c.value('(//@monitorLoop)[1]', 'INT') AS monitor_loop,
        c.query('.') AS blocked_process_report
FROM #human_events_xml AS xet
OUTER APPLY xet.human_events_xml.nodes('//event') AS oa(c)
) report
inner join ( select max(event_time) max_event_time
     , transaction_id
              from
              (
                      select dateadd(minute, datediff(minute, getutcdate(), sysdatetime()), c.value('@timestamp', 'DATETIME2')) as event_time
                             , c.value('(data[@name="transaction_id"]/value)[1]', 'BIGINT')                                       as transaction_id
                      from #human_events_xml                                as xet
                             outer apply xet.human_events_xml.nodes('//event') as oa(c)
              ) sub
              group by transaction_id ) max_event
on  max_event.max_event_time = report.event_time
and max_event.transaction_id = report.transaction_id

**Comment by erikdarlingdata** [comment]
I'd like to avoid using event time as an identifier as much as possible. Can you explain a little how this helps?

**Comment by ronaldgithub** [comment]
In step 1 the max event time is found based grouped by transaction
In step 2 just one //event is joined, so you don’t have a lot of records anymore
In step 3 and 4 it is easier (?) to parse the xml because it is in one column or call J. Keyhesian (this is so difficult, also when you hav namespaces involved..)..

Just a thought..

[cid:image001.jpg@01D5FBB3.024C72E0]

**Comment by erikdarlingdata** [comment]
Right, I get what the code does, but I'm trying to understand how it helps the situation you're running into? It doesn't look like you're doing an update anywhere.


/* erikdarlingdata.com */
/* sql server performance tuning */
________________________________

**Comment by ronaldgithub** [comment]
Yes you are right, but instead of each ‘loop’ you get one max record, I still have to figure out your code..
Perhaps an update from just the wait_time when the blocking session is still present..

**Comment by erikdarlingdata** [comment]
Okay, yeah, take a look at the code and let me know if you have any questions.


/* erikdarlingdata.com */
/* sql server performance tuning */
________________________________

**Comment by ronaldgithub** [comment]
I will, but I thought you mentioned in one of your videos that you thought about doing an ‘upsert’ ..

**Comment by erikdarlingdata** [comment]
Yep, and I did! There's an insert for new data, and an update for existing data.


/* erikdarlingdata.com */
/* sql server performance tuning */
________________________________

**Comment by ronaldgithub** [comment]
Give me some time, I will have a look tonight if I can figure it out..

**Comment by ronaldgithub** [comment]
UPDATE x2
    SET x2.wait_time = x.waittime
FROM [HumanEventsData].[dbo].keeper_HumanEvents_blocking AS x2
JOIN
(
    SELECT @@SERVERNAME AS server_name,
           'blocked' AS activity,
           c.value('(data[@name="database_id"]/value)[1]', 'INT') AS database_id,
           c.value('(data[@name="object_id"]/value)[1]', 'INT') AS object_id,
           c.value('(data[@name="transaction_id"]/value)[1]', 'BIGINT') AS transaction_id,
           bd.value('(process/@spid)[1]', 'INT') AS spid,
           bd.value('(process/@ecid)[1]', 'INT') AS ecid,
           bd.value('(process/@waittime)[1]', 'BIGINT') AS waittime,
           bd.value('(process/@clientapp)[1]', 'NVARCHAR(256)') AS clientapp,
           bd.value('(process/@hostname)[1]', 'NVARCHAR(256)') AS hostname,
           bd.value('(process/@loginname)[1]', 'NVARCHAR(256)') AS loginname
    FROM #human_events_xml_internal AS xet
    OUTER APPLY xet.human_events_xml.nodes('//event') AS oa(c)
    OUTER APPLY oa.c.nodes('//blocked-process-report/blocked-process') AS bd(bd)
) AS x
    ON    x.database_id = x2.database_id
    AND   x.object_id = x2.object_id

?     AND   x.transaction_id = x2.transaction_id

    AND   x.spid = x2.spid
    AND   x.ecid = x2.ecid
    AND   x.clientapp = x2.client_app
    AND   x.hostname = x2.host_name
    AND   x.loginname = x2.login_name
    AND   x.activity = x2.activity
OPTION (RECOMPILE);

**Comment by erikdarlingdata** [comment]
I understand that you're trying to help, and I appreciate it, but one of the most helpful things you can do is communicate clearly in these issues. We've been going back and forth a bit now. 

In your most recent addition, you've pasted the update statement with no comment, and a single question mark before a predicate. If you look at [the code in the dev branch](https://github.com/erikdarlingdata/DarlingData/blob/dev/sp_HumanEvents/sp_HumanEvents.sql#L2221), that predicate already exists (along with another one for monitor loop).

So help me out here -- what's your question? Do I need to remove it? Is there a reason you don't have monitor loop in there as well? Or that you're referencing code that's a few commits behind current? Or from a different branch? I'm just not sure what to make of this.

Please please please, to respect everyone's time, be clear in what you're posting.

Thanks,
Erik
